import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import {
  useDeleteUserMutation,
  useGetUsersQuery,
} from "../generated-graphql/graphql";
import styles from "../styles/Home.module.css";

type $fixMe = any;

export default function Home() {
  // const { data: usersData } = useGetUsersQuery()
  // const [deleteUser] = useDeleteUserMutation()
  // const router = useRouter()

  // React.useEffect(() => {
  //   router.push('/register')
  // }, [])

  // const onDelete = (id: $fixMe) => {

  //   deleteUser({
  //     variables: { id },
  //     update: (cache) => {
  //       cache.evict({ id: "User:" + id });
  //     },
  //   })
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Fullstack app sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Sample</a>
        </h1>

        <p className={styles.subtitle}>fullstack app </p>

        <div className={styles.grid}>
          {/* {usersData?.users.map(user => {
            return <>
                <div className={styles.card}>
                  <h2>{user.username}</h2>
                  <p>{user.email}</p>
                  <p 
                    style={{ marginTop: 20, cursor: 'pointer' }}
                    onClick={() => onDelete(user.id)}  
                  >Delete</p>
                </div>
              </>
          })} */}
        </div>
      </main>
    </div>
  );
}
