schema: 'http://localhost:4000/graphql'
documents: src/graphql/**/*.graphql
extensions:
  codegen:
    generates:
      src/generated-graphql/graphql.tsx:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
    overwrite: true
